MoveAnything_PredefinedCustomFrameList = {
	{ "Separator", "**** BankItems ****" },
	{ "BankItems_Frame", "BankItems Main Frame" },
	{ "BankItems_ContainerFrame1", "BankItems Bag 1" },
	{ "BankItems_ContainerFrame2", "BankItems Bag 2" },
	{ "BankItems_ContainerFrame3", "BankItems Bag 3" },
	{ "BankItems_ContainerFrame4", "BankItems Bag 4" },
	{ "BankItems_ContainerFrame5", "BankItems Bag 5" },
	{ "BankItems_ContainerFrame6", "BankItems Bag 6" },
	--{ "Separator", "**** Custom Windows ****" },
	{ "Separator", "**** ATSW ****" },
	{ "ATSW", "ATSWFrame" },
	{ "Separator", "**** Aux ****" },
	{ "Aux", "aux_frame" },
	{ "Separator", "**** SUCC_bag ****" },
	{ "SUCC_bag", "SUCC_bag" },
	{ "SUCC_bagBank", "SUCC_bagBank" },
	{ "Separator", "**** TWThreat ****" },
	{ "TWTMain", "TWTMain" },
};
